### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by izen1231** [Nanamare/android_architecture#1]
안녕하세요 메르시 팀 송주현입니다.
요즘 잘 지내고 계신가요? 카톡에서 사라지셔서 Issue로 남깁니다 ...

**Comment by Nanamare** [comment]
@izen1231 
안녕하세요 :) 잘 지내고 있습니다.
핸드폰을 도난당한 후 의도치않게 잠수를 타게 되었네요 ... 죄송합니다..!

**Comment by izen1231** [comment]
아하 그러셨군요

**Comment by izen1231** [comment]
다시 합류하실 생각은 있으신가요??
